#!/bin/bash

if grep -Fxq "function upa () {" ~/.bashrc
then
    echo "quick update function already exists"
else
    echo "adding quick update function"
    echo '
# add quick update function
function upa() {
    sudo apt update && sudo apt full-upgrade && sudo apt autoremove;
    sudo snap refresh;' >> ~/.bashrc
    if [ -f /usr/local/bin/yt-dlp ]
    then
        echo '    sudo yt-dlp -U;' >> ~/.bashrc
    fi
    echo '    # uncomment if retroarch is installed
    #flatpak update --user org.libretro.RetroArch;
}' >> ~/.bashrc
    echo '}' >> ~/.bashrc
fi
