#!/bin/bash

# set up window snapping on lubuntu
RC=~/.config/openbox/rc.xml
if [ -f "$RC" ];
then
    echo "lubuntu setup already done"
else
    mkdir -p ~/.config/openbox
    cp /etc/xdg/xdg-Lubuntu/openbox/rc.xml ~/.config/openbox/rc.xml
    sed -i -e "/<\/keyboard>/r rc_replacement.txt" -e "s///" ~/.config/openbox/rc.xml
    openbox --reconfigure
    echo
    echo 'Turn off "Super_L" in Menu > Preferences > LXQt settings > Shortcut Keys'
    echo
fi
