#!/bin/bash

if grep -Fxq "parse_git_branch() {" ~/.bashrc
then
    echo "git branch display already exists"
else
    echo "adding git branch display"
    echo "
# add git branch display
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}" >> ~/.bashrc
    echo 'PS1_partial=${PS1::-3}'>> ~/.bashrc
    echo 'PS1="$PS1_partial \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "'>> ~/.bashrc
fi
