#!/bin/bash

while true; do
    read -p "Is this a dual boot system? " resp
    case $resp in
        [Yy]* )
            # make linux use local time to play nice with windows
            timedatectl set-local-rtc 1 --adjust-system-clock;
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

while true; do
    read -p "Support tap to click? " resp
    case $resp in
        [Yy]* )
            sudo cp 30-touchpad.conf /etc/X11/xorg.conf.d/;
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

while true; do
    read -p "Keep libreoffice? " resp
    case $resp in
        [Yy]* )
            break;;
        [Nn]* )
            sudo apt-get remove --purge libreoffice*;
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

# removing packages
sudo apt clean
sudo apt autoremove
sudo apt remove featherpad vim noblenote 2048-qt skanlite quassel trojita k3b

# getting packages
sudo apt update
sudo apt full-upgrade
sudo apt install scite filezilla curl openssh-server blueman python-is-python3 screen flatpak
sudo apt autoremove

# getting youtube-dl
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

# getting retroarch
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --user flathub org.libretro.RetroArch

# change ssh port
while :; do
    read -ep 'Enter ssh port: ' port
    [[ $port =~ ^[[:digit:]]+$ ]] || continue
    (( ( (port=(10#$port)) <= 65535 ) && port >= 1023 )) || continue
    # checking for valid new port
    break
done
sudo sed -i "s/^#Port.*/Port $port/" /etc/ssh/sshd_config

# copy over scite properties
cp SciTEUser_properties ~/.SciTEUser.properties

# make easy update function
if grep -Fxq "function upa () {" ~/.bashrc
then
    echo "quick update function exists"
else
    echo "adding quick update function"
    echo '
# add quick update function
function upa () {
    sudo apt update && sudo apt full-upgrade && sudo apt autoremove
    sudo youtube-dl -U
    flatpak update --user org.libretro.RetroArch
}' >> ~/.bashrc
fi

# set up window snapping on lubuntu
while true; do
    read -p "Using Lubuntu? " resp
    case $resp in
        [Yy]* )
            if ! grep -Fq "<!-- window snapping -->" ~/.config/openbox/lxqt-rc.xml
            then
                sed -i -e "/  <\/keyboard>.*/r rc_replacement.txt" -e "s///" ~/.config/openbox/rc.xml;
                openbox --reconfigure;
            fi
            echo;
            echo 'Turn off "Super_L" in Menu > Preferences > LXQt settings > Shortcut Keys';
            echo;
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done
