#!/bin/bash

# setup script for a lubuntu / windows dual boot system

# make linux use local time to play nice with windows
timedatectl set-local-rtc 1 --adjust-system-clock

# removing packages
sudo apt-get remove --purge libreoffice*
sudo apt-get clean
sudo apt-get autoremove
sudo apt remove featherpad vim noblenote 2048-qt skanlite quassel trojita k3b

# getting packages
sudo apt update
sudo apt full-upgrade
sudo apt install scite filezilla curl openssh-server blueman python-is-python3 screen flatpak
sudo apt autoremove

# getting youtube-dl
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

# getting retroarch
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --user flathub org.libretro.RetroArch

# change ssh port
sed -i 's/^#Port.*/Port 2213' /etc/ssh/sshd_config

# go to start directory
cd ~

# make update function
if grep -Fxq "function upa () {" .bashrc
then
    echo "quick update function exists"
else
    echo "adding quick update function"
    echo '
# add quick update function
function upa () {
    sudo apt update && sudo apt full-upgrade && sudo apt autoremove
    sudo youtube-dl -U
    flatpak update --user org.libretro.RetroArch
}' >> .bashrc
fi

# edit scite properties
echo '# Show line numbers:
line.margin.visible=1

# Set tabs to 4 spaces:
tabsize=4
indent.size=4
use.tabs=0

# Show whitespaces:
view.whitespace=1

# Set monospaced font:
font.base=$(font.monospace)
font.small=$(font.monospace)
font.comment=$(font.monospace)
font.text=$(font.monospace)
font.text.comment=$(font.monospace)
font.embedded.base=$(font.monospace)
font.embedded.comment=$(font.monospace)
font.vbs=$(font.monospace)

# open files in the last directory:
open.dialog.in.file.directory=1

# show all files:
open.filter=$(all.files)Source Files (cpp,c,h,mak)|*.cpp;*.c;*.h;*.mak;makefile|Web Files (htm, html, css, xml, shtml, js, pl, asp)|*.html;*.htm;*.css;*.shtml;*.js;*.pl;*.xml;*.asp|Text (txt, doc)|*.txt;*.doc|

# show status bar:
statusbar.visible=1

# show full path in the SciTE application window title bar:
# (just the filename will remain in the tab caption)
title.full.path=1' >> .SciTEUser.properties
