#!/bin/bash

while true; do
    read -p "Remove libreoffice? " resp
    case $resp in
        [Yy]* )
            sudo apt-get remove --purge libreoffice*;
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

while true; do
    read -p "First time package setup? " resp
    case $resp in
        [Yy]* )
            # removing packages
            sudo apt clean
            sudo apt autoremove
            sudo apt remove featherpad vim noblenote 2048-qt skanlite quassel trojita k3b
            # getting packages
            sudo apt update
            sudo apt full-upgrade
            sudo apt install scite filezilla curl openssh-server blueman python-is-python3 screen p7zip-full xxd pngcrush ffmpeg
            sudo apt autoremove
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

# getting youtube-dl
if [ ! -f /usr/local/bin/youtube-dl ]
then
    sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
    sudo chmod a+rx /usr/local/bin/youtube-dl
fi

# getting retroarch
retroarch_installed=false
while true; do
    read -p "Retroarch setup? " resp
    case $resp in
        [Yy]* )
            sudo apt install flatpak
            flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
            flatpak install --user flathub org.libretro.RetroArch
            retroarch_installed=true
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

while true; do
    read -p "Is this a dual boot system? " resp
    case $resp in
        [Yy]* )
            # make linux use local time to play nice with windows
            timedatectl set-local-rtc 1 --adjust-system-clock;
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

while true; do
    read -p "Support tap to click? " resp
    case $resp in
        [Yy]* )
            sudo cp 30-touchpad.conf /etc/X11/xorg.conf.d/;
            break;;
        [Nn]* )
            break;;
        * ) echo "Answer yes or no.";;
    esac
done

# change ssh port
if grep -Fxq "#Port" /etc/ssh/sshd_config
then
    while :; do
        read -ep 'Enter ssh port: ' port
        [[ $port =~ ^[[:digit:]]+$ ]] || continue
        (( ( (port=(10#$port)) <= 65535 ) && port > 1024 )) || continue
        # checking for valid new port
        break
    done
    sudo sed -i "s/^#Port.*/Port $port/" /etc/ssh/sshd_config
else
    echo "ssh port has already been set"
fi

# copy over scite properties
cp SciTEUser_properties ~/.SciTEUser.properties

# set up git branch display
if grep -Fxq "parse_git_branch() {" ~/.bashrc
then
    echo "git branch display already exists"
else
    echo "adding git branch display"
    echo "
# add git branch display
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}" >> ~/.bashrc
    echo 'PS1_partial=${PS1::-3}'>> ~/.bashrc
    echo 'PS1="$PS1_partial \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$ "'>> ~/.bashrc
fi

# make easy update function
if grep -Fxq "function upa () {" ~/.bashrc
then
    echo "quick update function already exists"
else
    echo "adding quick update function"
    echo '
# add quick update function
function upa () {
    sudo apt update && sudo apt full-upgrade && sudo apt autoremove;' >> ~/.bashrc
    if [ -f /usr/local/bin/youtube-dl ]
    then
        echo '    sudo youtube-dl -U;' >> ~/.bashrc
    fi
    if [ "$retroarch_installed" = true ]
    then
        echo '    flatpak update --user org.libretro.RetroArch;' >> ~/.bashrc
    fi
    echo '}' >> ~/.bashrc
fi

# set up window snapping on lubuntu
if grep -Fq "<!-- window snapping -->" ~/.config/openbox/rc.xml
then
    echo "lubuntu setup already done"
else
    while true; do
        read -p "Using Lubuntu? " resp
        case $resp in
            [Yy]* )
                sed -i -e "/  <\/keyboard>.*/r rc_replacement.txt" -e "s///" ~/.config/openbox/rc.xml;
                openbox --reconfigure;
                echo;
                echo 'Turn off "Super_L" in Menu > Preferences > LXQt settings > Shortcut Keys';
                echo;
                break;;
            [Nn]* )
                break;;
            * ) echo "Answer yes or no.";;
        esac
    done
fi
